# Generated by Django 4.2.9 on 2024-06-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('secondname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=20, verbose_name='Отчество')),
                ('number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Cтатус работника')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('expirydate', models.DateField()),
                ('owner', models.CharField(max_length=100, verbose_name='Владелец')),
                ('registersdate', models.DateField(auto_now=True, verbose_name='Дата регистрации')),
                ('equipmentphoto', models.ImageField(upload_to='', verbose_name='Фото')),
                ('store', models.CharField(max_length=100, verbose_name='Место нахождения')),
            ],
        ),
        migrations.CreateModel(
            name='Foremans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('secondname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('password', models.CharField(max_length=15, verbose_name='Пароль')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Cтатус работника')),
            ],
        ),
        migrations.CreateModel(
            name='Foremans2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('secondname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('status', models.CharField(max_length=100, verbose_name='Cтатус работника')),
            ],
        ),
        migrations.CreateModel(
            name='man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('secondname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=20, verbose_name='Отчество')),
                ('number', models.CharField(max_length=10, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='passport_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_object', models.CharField(max_length=100, verbose_name='Имя объекта')),
                ('orderer', models.CharField(max_length=100, verbose_name='Заказчик')),
                ('location', models.FloatField(verbose_name='Локация в координатах')),
            ],
        ),
        migrations.CreateModel(
            name='plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=100, verbose_name='Задачи')),
                ('quantityday', models.IntegerField(verbose_name='Количество дней')),
                ('secondnamebuilders', models.TextField(max_length=200, verbose_name='Фамилия рабочего')),
                ('equip', models.TextField(max_length=200, verbose_name='Техника')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
            ],
        ),
    ]
