# Generated by Django 4.2.9 on 2024-06-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='man',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cтатус работника'),
        ),
    ]
