# Generated by Django 4.2.9 on 2024-06-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_equipment_names_remove_equipment_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='man',
            name='hourweek',
            field=models.IntegerField(default=0, verbose_name='Часы работника за неделю'),
        ),
    ]
